[DOC IMP] Add Configure-TI-CC2541-compatible-proprietary-PHY CN version
MarkDing/IoT-Developer-Boot-Camp-Wiki pull request #120
Opened 2020-12-28 07:33 UTC by silabs-EricS

[DOC IMP] Add Configure-TI-CC2541-compatible-proprietary-PHY CN version, also have some slight improvement on EN version.
Please help to review and approval.

@MarkDing @ChengYuan-CY

2020-12-29 01:19 UTC, ChengYuan-CY requested changes
@silabs-EricS I have few comments about the CN version.

2020-12-29 01:19 UTC, ChengYuan-CY commented on proprietary/Configure-TI-CC2541-compatible-proprietary-PHY-CN.md
> +CC2541EMK 与 BRD4182A一样, 支持 Proprietary, 可以与BRD4182A进行通信. 通过 MS2692A 可以从它的空中信号获得一些未知的特性或参数.
通过频谱分析仪MS2692A

2020-12-29 01:19 UTC, ChengYuan-CY commented on proprietary/Configure-TI-CC2541-compatible-proprietary-PHY-CN.md
> +如图, Marker1 与 Marker2 之间的间隔时间是 52us. 13字节的前导码, 2Mbps 意味着第个比特占 0.5us, 13 x 8 x 0.5us = 52us, 所以可以判断这个是前导码. MS2629A 检测到1字节的前导码与48us载波信号, 目前还没搞明白其原因, 检查了 TI BLE PHY等其他2M PHY, 也存在这样的问题. 之前提到按已知参数配置 EFR32
MS2629A 检测到1字节的前导码与48us载波信号, 同时我们检查了 TI BLE PHY等其他2M PHY, 也存在这样的问题，由此我们可以得知，CC2541仅发送了1字节的前导码及48us载波信号，而非完整的13字节前导码。

2020-12-30 02:59 UTC, silabs-EricS commented on proprietary/Configure-TI-CC2541-compatible-proprietary-PHY-CN.md
> +有时会收到这样的需求, 配置与其他供应商的设备兼容的 PHY(Physical Layer / 物理层), 以便两者进行通信. 这里分享配置EFR32xG22 PHY 与 TI CC2541 [Proprietary(专有协议) 2.4G PHY](files/PR-Configure-TI-CC2541-compatible-proprietary-PHY/2M_BS-TX_2.xml) 通信
是同步字。
相似相同的问题，怎么写应该都可能会有人有疑问。
因为完成相同，可能做不到。
而相似，有些参数允许一定量的差异，有些又不允许。细节私底下讨论。
与英文版同步，只写相同。

2021-01-05 02:06 UTC, merged